$ErrorActionPreference = "Stop"

if (Test-Path Variable:PSNativeCommandUseErrorActionPreference) {
  $PSNativeCommandUseErrorActionPreference = $false
}

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
$rootCandidate = Split-Path -Parent $PSScriptRoot
$root = if (Test-Path -LiteralPath (Join-Path $rootCandidate "owlbox/OUTLINE.md")) { $rootCandidate } else { (Get-Location).Path }

$sourcePaths = @(
  "owlbox/OUTLINE.md",
  "owlbox/WISDOM.md"
)

$legacyPath = Join-Path $root "owlbox/LEGACY.md"
$hootPath = Join-Path $root "HOOT.md"
$originalPath = Join-Path $root "ORIGINAL.md"

$legacyHeader = @(
  "LEGACY.md is generated by scripts/hoot-hoot.ps1. Never edit this file directly.",
  "New Log entries come only from changes to OUTLINE.md and WISDOM.md. Existing Log entries shall never be changed or deleted.",
  "",
  "---- ^ PERMANENT HEADER DO NOT EDIT ^ ----",
  "",
  "# LEGACY.md",
  "",
  "## Log",
  ""
) -join "`n"

function Normalize-Text {
  param([AllowEmptyString()][string]$Text)

  if ($null -eq $Text) { $Text = "" }
  $normalized = $Text -replace "`r`n", "`n" -replace "`r", "`n"
  if ($normalized.Length -eq 0) { return "" }
  return $normalized.TrimEnd([char[]]"`n") + "`n"
}

function Write-Utf8 {
  param([string]$Path, [string]$Text)
  [System.IO.File]::WriteAllText($Path, $Text, $utf8NoBom)
}

function Get-Sha256 {
  param([string]$Text)

  $sha = [System.Security.Cryptography.SHA256]::Create()
  try {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Text)
    return (($sha.ComputeHash($bytes) | ForEach-Object { "{0:x2}" -f $_ }) -join "")
  } finally {
    $sha.Dispose()
  }
}

function Get-ContextDiff {
  param([string]$Before, [string]$After)

  $beforePath = [System.IO.Path]::GetTempFileName()
  $afterPath = [System.IO.Path]::GetTempFileName()

  try {
    Write-Utf8 $beforePath $Before
    Write-Utf8 $afterPath $After

    $output = @(& git diff --no-index --unified=2 --text -- $beforePath $afterPath 2>&1)
    $exitCode = $LASTEXITCODE

    if ($exitCode -gt 1) {
      throw "git diff failed: $($output -join "`n")"
    }

    $body = foreach ($line in $output) {
      $text = $line.ToString()
      if ($text -notmatch '^diff --git ' -and
          $text -notmatch '^index ' -and
          $text -notmatch '^--- ' -and
          $text -notmatch '^\+\+\+ ' -and
          $text -notmatch '^warning: ') {
        if ($text -eq " ") { "" } else { $text }
      }
    }

    return ($body -join "`n")
  } finally {
    Remove-Item -LiteralPath $beforePath, $afterPath -Force -ErrorAction SilentlyContinue
  }
}

$gitStatePathOutput = @(& git -C $root rev-parse --git-path owlbox-legacy-state.json 2>&1)
if ($LASTEXITCODE -ne 0) {
  throw "Owlbox requires a Git repository: $($gitStatePathOutput -join "`n")"
}

$gitStatePathText = $gitStatePathOutput[0].ToString().Trim()
$statePath = if ([System.IO.Path]::IsPathRooted($gitStatePathText)) { $gitStatePathText } else { Join-Path $root $gitStatePathText }

$current = @{}
foreach ($source in $sourcePaths) {
  $path = Join-Path $root $source
  if (-not (Test-Path -LiteralPath $path)) {
    throw "Missing Owlbox source: $source"
  }
  $current[$source] = Normalize-Text (Get-Content -LiteralPath $path -Raw -Encoding utf8)
}

$legacyExisted = Test-Path -LiteralPath $legacyPath
$stateExisted = Test-Path -LiteralPath $statePath
$legacyChanged = $false

if ($legacyExisted) {
  $legacy = Get-Content -LiteralPath $legacyPath -Raw -Encoding utf8
  if (-not $legacy.StartsWith("LEGACY.md is generated by scripts/hoot-hoot.ps1.")) {
    if (-not (Test-Path -LiteralPath $originalPath)) {
      throw "Create ORIGINAL.md before converting the earlier LEGACY.md format."
    }
    $preserved = $legacy.TrimEnd([char[]]"`r`n")
    $legacy = $legacyHeader + "### Pre-generation Legacy`n`n" + '````text' + "`n" + $preserved + "`n" + '````' + "`n"
    $legacyChanged = $true
  } else {
    $legacy = Normalize-Text $legacy
  }
} else {
  $legacy = $legacyHeader
  $legacyChanged = $true
}

$previous = @{}
if ($stateExisted) {
  $state = Get-Content -LiteralPath $statePath -Raw -Encoding utf8 | ConvertFrom-Json
  $previous["owlbox/OUTLINE.md"] = [string]$state.outline
  $previous["owlbox/WISDOM.md"] = [string]$state.wisdom
} elseif ($legacyExisted) {
  foreach ($source in $sourcePaths) {
    $previous[$source] = $current[$source]
  }
} else {
  foreach ($source in $sourcePaths) {
    $previous[$source] = ""
  }
}

foreach ($source in $sourcePaths) {
  $before = Normalize-Text $previous[$source]
  $after = $current[$source]

  if ($before -eq $after) { continue }

  $hash = Get-Sha256 $after
  $revision = "Revision: sha256:$hash"
  if ($legacy.Contains($revision)) { continue }

  $diff = Get-ContextDiff $before $after
  if ([string]::IsNullOrWhiteSpace($diff)) { continue }

  $timestamp = Get-Date -Format "MM/dd/yy HH:mm:ss"
  $name = Split-Path -Leaf $source
  $entry = @(
    "",
    "### $timestamp - $name change",
    "",
    $revision,
    "",
    '```diff',
    $diff,
    '```',
    ""
  ) -join "`n"

  $legacy = $legacy.TrimEnd([char[]]"`n") + $entry
  $legacyChanged = $true
}

if ($legacyChanged) {
  Write-Utf8 $legacyPath (Normalize-Text $legacy)
}

$state = [ordered]@{
  version = 1
  outline = $current["owlbox/OUTLINE.md"]
  wisdom = $current["owlbox/WISDOM.md"]
}
Write-Utf8 $statePath ((ConvertTo-Json $state -Depth 3) + "`n")

$hootContent = @(
  "# HOOT.md",
  "",
  "Generated from canonical OWL files. Do not edit this file directly.",
  ""
)

foreach ($source in @("owlbox/OUTLINE.md", "owlbox/WISDOM.md", "owlbox/LEGACY.md")) {
  $path = Join-Path $root $source
  if (-not (Test-Path -LiteralPath $path)) {
    throw "Missing Owlbox file: $source"
  }
  $hootContent += Get-Content -LiteralPath $path -Encoding utf8
  $hootContent += ""
}

Write-Utf8 $hootPath (($hootContent -join "`n") + "`n")
