# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Michael Christian Haley

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$sources = @(
  "PROJECT.md",
  "VERSION",
  "RELEASE.md",
  "LICENSE.md",
  "CONTRIBUTORS.md",
  "ORIGINAL.md",
  "MANIFEST.md",
  "SOP.md",
  "FILES.md",
  "DELIVERABLES.md",
  "TEMPLATES.md",
  "BUILDABOX.md",
  "templates/OUTLINE.template.md",
  "templates/WISDOM.template.md",
  "templates/LEGACY.template.md",
  "assistant/owlbox/SKILL.md",
  "assistant/owlbox-outline/SKILL.md",
  "assistant/owlbox-wisdom/SKILL.md",
  "assistant/owlbox-legacy/SKILL.md",
  "assistant/owlbox/assets/OUTLINE.template.md",
  "assistant/owlbox/assets/WISDOM.template.md",
  "assistant/owlbox/assets/LEGACY.template.md",
  "assistant/owlbox/scripts/hoot-hoot.ps1",
  "scripts/hoot-hoot.ps1",
  "scripts/build-readme.ps1",
  "scripts/build-vision.ps1",
  "scripts/build-all.ps1"
)

$content = @(
  "# VISION.md",
  "",
  "Generated from the canonical publication sources listed in scripts/build-vision.ps1. Do not edit this file directly.",
  "",
  "VISION.md is a publication artifact for the Owlbox system. It is not the same as HOOT.md.",
  ""
)

foreach ($source in $sources) {
  $path = Join-Path $root $source
  if (-not (Test-Path -LiteralPath $path)) {
    throw "Missing VISION source: $source"
  }
  $content += "--- $source ---"
  $content += ""
  $content += Get-Content $path -Encoding utf8
  $content += ""
}

$output = Join-Path $root "VISION.md"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

function Write-Utf8 {
  param([string]$Path, [AllowEmptyString()][string]$Text)

  $bytes = $utf8NoBom.GetBytes($Text)
  if (Test-Path -LiteralPath $Path) {
    $existing = [System.IO.File]::ReadAllBytes($Path)
    if ($existing.Length -eq $bytes.Length) {
      $same = $true
      for ($index = 0; $index -lt $bytes.Length; $index++) {
        if ($existing[$index] -ne $bytes[$index]) { $same = $false; break }
      }
      if ($same) { return }
    }
  }

  $directory = Split-Path -Parent $Path
  $temporaryPath = Join-Path $directory (".$([System.IO.Path]::GetFileName($Path)).$([guid]::NewGuid().ToString('N')).tmp")
  $backupPath = Join-Path $directory (".$([System.IO.Path]::GetFileName($Path)).$([guid]::NewGuid().ToString('N')).bak")
  try {
    [System.IO.File]::WriteAllBytes($temporaryPath, $bytes)
    if (Test-Path -LiteralPath $Path) { [System.IO.File]::Replace($temporaryPath, $Path, $backupPath) } else { [System.IO.File]::Move($temporaryPath, $Path) }
  } finally {
    if (Test-Path -LiteralPath $temporaryPath) { Remove-Item -LiteralPath $temporaryPath -Force -ErrorAction SilentlyContinue }
    if (Test-Path -LiteralPath $backupPath) { Remove-Item -LiteralPath $backupPath -Force -ErrorAction SilentlyContinue }
  }
}

Write-Utf8 $output (($content -join "`n") + "`n")
