$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$sources = @(
  "PROJECT.md",
  "ORIGINAL.md",
  "SOP.md",
  "FILES.md",
  "DELIVERABLES.md",
  "TEMPLATES.md",
  "BUILDABOX.md",
  "templates/OUTLINE.template.md",
  "templates/WISDOM.template.md",
  "assistant/owlbox/SKILL.md",
  "assistant/owlbox-outline/SKILL.md",
  "assistant/owlbox-wisdom/SKILL.md",
  "assistant/owlbox-legacy/SKILL.md",
  "assistant/owlbox/assets/OUTLINE.template.md",
  "assistant/owlbox/assets/WISDOM.template.md",
  "assistant/owlbox/scripts/hoot-hoot.ps1",
  "scripts/hoot-hoot.ps1",
  "scripts/build-readme.ps1",
  "scripts/build-vision.ps1",
  "scripts/build-all.ps1"
)

$content = @(
  "# VISION.md",
  "",
  "Generated from Owlbox repository project files. Do not edit this file directly.",
  "",
  "VISION.md is a publication artifact for the Owlbox system. It is not the same as HOOT.md.",
  ""
)

foreach ($source in $sources) {
  $path = Join-Path $root $source
  if (-not (Test-Path -LiteralPath $path)) {
    throw "Missing VISION source: $source"
  }
  $content += "--- $source ---"
  $content += ""
  $content += Get-Content $path -Encoding utf8
  $content += ""
}

$output = Join-Path $root "VISION.md"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($output, (($content -join "`n") + "`n"), $utf8NoBom)
