$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$sources = @(
  "owlbox/OUTLINE.md",
  "owlbox/WISDOM.md",
  "owlbox/LEGACY.md"
)

$content = @(
  "# OWLBOX.md",
  "",
  "Generated from canonical OWL files. Do not edit this file directly.",
  ""
)

foreach ($source in $sources) {
  $path = Join-Path $root $source
  $content += Get-Content $path -Encoding utf8
  $content += ""
}

$content | Set-Content (Join-Path $root "OWLBOX.md") -Encoding utf8


