$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$sources = @(
  "PROJECT.md",
  "SOP.md",
  "FILES.md",
  "DELIVERABLES.md",
  "TEMPLATES.md",
  "BUILDABOX.md",
  "templates/OUTLINE.template.md",
  "templates/WISDOM.template.md",
  "templates/LEGACY.template.md",
  "codex/owlbox/SKILL.md",
  "codex/owlbox/assets/OUTLINE.template.md",
  "codex/owlbox/assets/WISDOM.template.md",
  "codex/owlbox/assets/LEGACY.template.md",
  "codex/owlbox/scripts/build-owlbox.ps1",
  "scripts/build-owlbox.ps1",
  "scripts/build-readme.ps1",
  "scripts/build-vision.ps1",
  "scripts/build-all.ps1"
)

$content = @(
  "# VISION.md",
  "",
  "Generated from Owlbox repository project files. Do not edit this file directly.",
  "",
  "VISION.md is a publication artifact for the Owlbox system. It is not the same as OWLBOX.md.",
  ""
)

foreach ($source in $sources) {
  $path = Join-Path $root $source
  if (Test-Path $path) {
    $content += "===== $source ====="
    $content += ""
    $content += Get-Content $path -Encoding utf8
    $content += ""
  }
}

$content | Set-Content (Join-Path $root "VISION.md") -Encoding utf8
