$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$sources = @(
  "owlbox/OUTLINE.md",
  "owlbox/WISDOM.md",
  "owlbox/LEGACY.md"
)

$content = @(
  "# HOOT.md",
  "",
  "Generated from canonical OWL files. Do not edit this file directly.",
  ""
)

foreach ($source in $sources) {
  $path = Join-Path $root $source
  if (-not (Test-Path -LiteralPath $path)) {
    throw "Missing Owlbox source: $source"
  }
  $content += Get-Content $path -Encoding utf8
  $content += ""
}

$output = Join-Path $root "HOOT.md"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($output, (($content -join "`n") + "`n"), $utf8NoBom)
